name: CI/CD NestJS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get package version
        id: package
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: alx52
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            alx52/nodejs-hello-api:${{ needs.build.outputs.version }}
            alx52/nodejs-hello-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build, publish]
    steps:
      - name: Checkout charts repository
        uses: actions/checkout@v3
        with:
          repository: alexalmeida52/gitops-apps
          token: ${{ secrets.GITOPS_TOKEN }} # Personal Access Token com permissão de push
          ref: develop   # ou hml/prd dependendo da branch da aplicação

      - name: Update Charts
        run: |
          sed -i "s|tag: .*|tag: \"${{ needs.build.outputs.version }}\"|" charts/values/nodejs-hello-api-values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/values/nodejs-hello-api-values.yaml
          git commit -m "update tag to ${{ needs.build.outputs.version }}"
          git push origin HEAD:develop
